from __future__ import annotations

from dataclasses import dataclass
from typing import Any

import yaml

from agentblaster.errors import ConfigError
from agentblaster.models import BenchmarkCase, SuiteDefinition, SuiteProvenance
from agentblaster.toolsim import SAFE_TOOL_SCHEMAS


@dataclass(frozen=True)
class AgentProfile:
    id: str
    display_name: str
    description: str
    representative_features: tuple[str, ...]


AGENT_PROFILES: tuple[AgentProfile, ...] = (
    AgentProfile(
        id="opencode",
        display_name="OpenCode-style coding agent",
        description="Repository triage, file inspection, shell/test loop, skill prefix, and deterministic tool replay.",
        representative_features=("repo tools", "shell fixture", "skills", "trace replay"),
    ),
    AgentProfile(
        id="openclaw",
        display_name="OpenClaw-style local tool parser agent",
        description="Strict API-native tool envelopes, parser stress, structured output, and local-model compatibility pressure.",
        representative_features=("required tools", "structured output", "parser strictness", "local model"),
    ),
    AgentProfile(
        id="hermes",
        display_name="Nous Hermes-style multi-tool agent",
        description="Planner loop, browser/search/file tools, MCP fixture expansion, LCP context bundles, memory-like context, and delegation pressure.",
        representative_features=("planner", "browser fixture", "MCP", "LCP", "multi-tool"),
    ),
    AgentProfile(
        id="pi",
        display_name="Pi-style local compatibility agent",
        description="Lean local-provider compatibility, simple chat, trace replay, and structured summary without advanced role assumptions.",
        representative_features=("lean prompts", "trace replay", "structured summary", "local provider"),
    ),
    AgentProfile(
        id="aider",
        display_name="Aider-style pair-programming agent",
        description="Patch-oriented coding loop with explicit file context, deterministic diff reasoning, and replayed test feedback.",
        representative_features=("pair programming", "diff reasoning", "test replay", "repo tools"),
    ),
    AgentProfile(
        id="cline",
        display_name="Cline-style plan/action agent",
        description="Stepwise plan, file inspection action, bounded command execution, and explicit final status.",
        representative_features=("plan-act loop", "file tools", "shell fixture", "bounded actions"),
    ),
    AgentProfile(
        id="continue",
        display_name="Continue-style IDE retrieval agent",
        description="IDE-local retrieval, documentation lookup, and concise structured engineering summary.",
        representative_features=("IDE retrieval", "docs search", "structured summary", "local provider"),
    ),
    AgentProfile(
        id="codex",
        display_name="Codex-style sandboxed coding agent",
        description="Sandbox-aware command planning, safe shell replay, concise final answer, and no host-tool escalation.",
        representative_features=("sandbox policy", "shell fixture", "concise final", "auditability"),
    ),
)


def list_agent_profiles() -> list[AgentProfile]:
    return list(AGENT_PROFILES)


def get_agent_profile(profile_id: str) -> AgentProfile:
    for profile in AGENT_PROFILES:
        if profile.id == profile_id:
            return profile
    available = ", ".join(profile.id for profile in AGENT_PROFILES)
    raise ConfigError(f"unknown agent profile: {profile_id}; available profiles: {available}")


def generate_agent_suite(profile_id: str, *, include_all: bool = False) -> SuiteDefinition:
    if include_all:
        cases: list[BenchmarkCase] = []
        for profile in AGENT_PROFILES:
            cases.extend(_profile_cases(profile.id))
        return _suite("agentic-local-profiles", "Representative local-agent workflow profiles for common local coding and tool-using agent patterns.", cases)
    profile = get_agent_profile(profile_id)
    return _suite(
        f"agentic-{profile.id}",
        f"Representative {profile.display_name} workload generated by AgentBlaster.",
        _profile_cases(profile.id),
    )


def suite_to_yaml(suite: SuiteDefinition) -> str:
    return yaml.safe_dump(suite.model_dump(mode="json", exclude_none=True), sort_keys=False, allow_unicode=False) + "\n"


def _suite(name: str, description: str, cases: list[BenchmarkCase]) -> SuiteDefinition:
    return SuiteDefinition(
        name=name,
        description=description,
        provenance=SuiteProvenance(
            origin="synthetic_representative",
            generator="agentblaster.agent_profiles",
            primary_source="AgentBlaster synthetic representative profiles",
            license="MIT",
            risk_labels=["synthetic", "representative", "agent-profile"],
            notes=[
                "Generated profile suites are representative harness fixtures, not claims about exact upstream agent internals.",
                "Use these suites to compare provider behavior under common local-agent prompt/tool shapes.",
            ],
        ),
        cases=cases,
    )


def _profile_cases(profile_id: str) -> list[BenchmarkCase]:
    if profile_id == "opencode":
        return _opencode_cases()
    if profile_id == "openclaw":
        return _openclaw_cases()
    if profile_id == "hermes":
        return _hermes_cases()
    if profile_id == "pi":
        return _pi_cases()
    if profile_id == "aider":
        return _aider_cases()
    if profile_id == "cline":
        return _cline_cases()
    if profile_id == "continue":
        return _continue_cases()
    if profile_id == "codex":
        return _codex_cases()
    raise ConfigError(f"unknown agent profile: {profile_id}")


def _opencode_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="opencode-read-plan",
            title="OpenCode-style repository read before plan",
            scenario="code edit loop",
            system_prompt="You are a local coding agent. Use fixture tools only and keep the final answer concise.",
            prompt="Inspect /repo/src/app.py with read_file_fixture before answering. Report the exact status string.",
            expected_tool_name="read_file_fixture",
            expected_tool_result_substring="agentblaster-ok",
            simulated_tools=["read_file_fixture"],
            tools=[SAFE_TOOL_SCHEMAS["read_file_fixture"]],
            tool_choice={"type": "function", "function": {"name": "read_file_fixture"}},
            skills=["repo-triage", "safe-tool-replay"],
            metrics=["ttft_ms", "tool_calls_valid", "tokens_per_second_decode"],
            max_tokens=96,
            tags=["agent-profile", "opencode", "code", "toolcall"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
        BenchmarkCase(
            id="opencode-test-loop-trace",
            title="OpenCode-style test loop trace replay",
            scenario="code edit loop",
            prompt="Use the replayed test output and answer whether the fixture tests passed.",
            messages=[
                {"role": "system", "content": "You are replaying a safe coding-agent test loop. Answer from tool results only."},
                {"role": "user", "content": "Run pytest -q."},
                {"role": "assistant", "content": "", "tool_calls": [{"id": "call_pytest", "type": "function", "function": {"name": "shell_fixture", "arguments": '{"command":"pytest -q"}'}}]},
                {"role": "tool", "name": "shell_fixture", "tool_call_id": "call_pytest", "content": '{"command":"pytest -q","exit_code":0,"stdout":"3 passed\n","stderr":""}'},
                {"role": "user", "content": "Did the tests pass? Reply with exactly: agentblaster-ok"},
            ],
            expected_substring="agentblaster-ok",
            skills=["repo-triage", "agent-planning"],
            metrics=["latency_ms", "tokens_per_second_decode"],
            max_tokens=32,
            tags=["agent-profile", "opencode", "trace-replay", "tests"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
    ]


def _openclaw_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="openclaw-required-tool-envelope",
            title="OpenClaw-style strict required tool envelope",
            scenario="tool parser strictness",
            system_prompt="Emit API-native tool calls only when a tool is required. Do not describe JSON or XML as plain text.",
            prompt="Call search_docs with query set to AgentBlaster PRD.",
            expected_tool_name="search_docs",
            expected_tool_result_substring="local agentic inference engines",
            simulated_tools=["search_docs"],
            tools=[SAFE_TOOL_SCHEMAS["search_docs"]],
            tool_choice={"type": "function", "function": {"name": "search_docs"}},
            metrics=["tool_calls_emitted", "tool_calls_valid", "invalid_tool_call_count"],
            max_tokens=80,
            tags=["agent-profile", "openclaw", "parser", "toolcall"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
        BenchmarkCase(
            id="openclaw-structured-local-summary",
            title="OpenClaw-style structured local summary",
            scenario="structured output",
            system_prompt="Return only valid JSON. No markdown and no raw tool transcript.",
            prompt='Return exactly this JSON object: {"status":"agentblaster-ok","tool_parser":"api-native"}',
            expected_json_fields={"status": "agentblaster-ok", "tool_parser": "api-native"},
            response_format={"type": "json_object"},
            metrics=["structured_output_valid", "latency_ms"],
            max_tokens=80,
            tags=["agent-profile", "openclaw", "structured", "local-model"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
    ]


def _hermes_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="hermes-mcp-planner-tool",
            title="Hermes-style planner with MCP fixture catalog",
            scenario="multi-tool planner",
            system_prompt="Use a compact planner step, then call the provided MCP-style fixture tool when useful.",
            prompt="Call mcp_echo with value set to agentblaster-ok.",
            expected_tool_name="mcp_echo",
            expected_tool_result_substring="agentblaster-ok",
            simulated_tools=["mcp_echo"],
            tools=[SAFE_TOOL_SCHEMAS["mcp_echo"]],
            tool_choice={"type": "function", "function": {"name": "mcp_echo"}},
            mcp_profile="fixture-mcp",
            skills=["agent-planning", "safe-tool-replay"],
            metrics=["ttft_ms", "tool_calls_valid", "tokens_per_second_prefill"],
            max_tokens=96,
            tags=["agent-profile", "hermes", "mcp", "planner"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
        BenchmarkCase(
            id="hermes-browser-memory-summary",
            title="Hermes-style browser and memory summary",
            scenario="search and summarize loop",
            system_prompt="Treat browser results as deterministic memory. Do not access the real network.",
            prompt="Use browser_fetch_fixture for https://example.test/agentblaster, then answer with exactly: agentblaster-ok",
            expected_tool_name="browser_fetch_fixture",
            expected_tool_result_substring="AgentBlaster fixture page",
            simulated_tools=["browser_fetch_fixture"],
            tools=[SAFE_TOOL_SCHEMAS["browser_fetch_fixture"]],
            tool_choice={"type": "function", "function": {"name": "browser_fetch_fixture"}},
            skills=["agent-planning"],
            metrics=["latency_ms", "tool_calls_valid"],
            max_tokens=96,
            tags=["agent-profile", "hermes", "browser", "memory"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
        BenchmarkCase(
            id="hermes-lcp-context-boundary",
            title="Hermes-style LCP scoped context boundary",
            scenario="local context protocol",
            system_prompt="Use the attached deterministic LCP context bundle only. Do not infer host filesystem, browser, or memory state beyond the bundle.",
            prompt="From the LCP fixture context, report the project status sentinel exactly.",
            expected_substring="agentblaster-lcp-ok",
            lcp_profile="fixture-lcp",
            skills=["agent-planning"],
            metrics=["ttft_ms", "tokens_per_second_prefill", "latency_ms"],
            max_tokens=48,
            tags=["agent-profile", "hermes", "lcp", "context-boundary"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
    ]


def _pi_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="pi-lean-local-chat",
            title="Pi-style lean local chat compatibility",
            scenario="local provider compatibility",
            system_prompt="Use plain assistant output. Avoid advanced role assumptions and keep the answer short.",
            prompt="Reply with exactly: agentblaster-ok",
            expected_substring="agentblaster-ok",
            metrics=["latency_ms", "tokens_per_second_decode"],
            max_tokens=16,
            tags=["agent-profile", "pi", "lean", "chat"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
        BenchmarkCase(
            id="pi-compatible-json-summary",
            title="Pi-style provider-compatible JSON summary",
            scenario="structured output",
            system_prompt="Return only valid JSON with no markdown.",
            prompt='Return exactly this JSON object: {"status":"agentblaster-ok","mode":"local-compatible"}',
            expected_json_fields={"status": "agentblaster-ok", "mode": "local-compatible"},
            response_format={"type": "json_object"},
            metrics=["structured_output_valid", "latency_ms"],
            max_tokens=64,
            tags=["agent-profile", "pi", "structured", "compatibility"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        ),
    ]


def _aider_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="aider-diff-test-replay",
            title="Aider-style patch and test replay",
            scenario="pair programming patch loop",
            prompt="Inspect the fixture repository, replay the tests, and summarize with exactly: agentblaster-ok",
            messages=[
                {"role": "system", "content": "You are replaying a pair-programming agent loop. Use only fixture context."},
                {"role": "user", "content": "Inspect /repo/src/app.py, infer the one-line status behavior, then use the replayed tests."},
                {"role": "assistant", "content": "", "tool_calls": [{"id": "call_read", "type": "function", "function": {"name": "read_file_fixture", "arguments": '{"path":"/repo/src/app.py"}'}}]},
                {"role": "tool", "name": "read_file_fixture", "tool_call_id": "call_read", "content": '{"path":"/repo/src/app.py","content":"agentblaster-ok"}'},
                {"role": "assistant", "content": "", "tool_calls": [{"id": "call_test", "type": "function", "function": {"name": "shell_fixture", "arguments": '{"command":"pytest -q"}'}}]},
                {"role": "tool", "name": "shell_fixture", "tool_call_id": "call_test", "content": '{"command":"pytest -q","exit_code":0,"stdout":"3 passed\\n","stderr":""}'},
                {"role": "user", "content": "Summarize the outcome with exactly: agentblaster-ok"},
            ],
            expected_substring="agentblaster-ok",
            simulated_tools=["read_file_fixture", "shell_fixture"],
            tools=[SAFE_TOOL_SCHEMAS["read_file_fixture"], SAFE_TOOL_SCHEMAS["shell_fixture"]],
            skills=["repo-triage", "safe-tool-replay"],
            metrics=["latency_ms", "tool_calls_valid", "tokens_per_second_decode"],
            max_tokens=48,
            tags=["agent-profile", "aider", "pair-programming", "trace-replay"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        )
    ]


def _cline_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="cline-plan-act-read",
            title="Cline-style plan/action file inspection",
            scenario="plan action loop",
            system_prompt="Create a brief plan internally, then use exactly one fixture action before the final answer.",
            prompt="Read /repo/README.md with read_file_fixture and answer with exactly: agentblaster-ok",
            expected_tool_name="read_file_fixture",
            expected_tool_result_substring="Fixture Repo",
            simulated_tools=["read_file_fixture"],
            tools=[SAFE_TOOL_SCHEMAS["read_file_fixture"]],
            tool_choice={"type": "function", "function": {"name": "read_file_fixture"}},
            skills=["agent-planning", "repo-triage"],
            metrics=["ttft_ms", "tool_calls_valid", "tool_loop_rounds"],
            max_tokens=80,
            tags=["agent-profile", "cline", "plan-act", "file-tools"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        )
    ]


def _continue_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="continue-doc-retrieval-summary",
            title="Continue-style IDE retrieval summary",
            scenario="IDE retrieval",
            system_prompt="Use deterministic retrieval context only and return compact JSON.",
            prompt='Search docs for "security policy" and return {"status":"agentblaster-ok","source":"docs"}',
            expected_tool_name="search_docs",
            expected_tool_result_substring="Raw API keys must never appear",
            simulated_tools=["search_docs"],
            tools=[SAFE_TOOL_SCHEMAS["search_docs"]],
            tool_choice={"type": "function", "function": {"name": "search_docs"}},
            response_format={"type": "json_object"},
            expected_json_fields={"status": "agentblaster-ok", "source": "docs"},
            skills=["repo-triage"],
            metrics=["structured_output_valid", "tool_calls_valid", "latency_ms"],
            max_tokens=96,
            tags=["agent-profile", "continue", "retrieval", "structured"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        )
    ]


def _codex_cases() -> list[BenchmarkCase]:
    return [
        BenchmarkCase(
            id="codex-sandbox-command-plan",
            title="Codex-style sandboxed command plan",
            scenario="sandboxed command planning",
            system_prompt="You are a sandbox-aware coding agent. Use only the deterministic shell fixture and do not request host escalation.",
            prompt="Use shell_fixture to run python -m agentblaster --version, then answer with exactly: agentblaster-ok",
            expected_tool_name="shell_fixture",
            expected_tool_result_substring="0.1.0",
            simulated_tools=["shell_fixture"],
            tools=[SAFE_TOOL_SCHEMAS["shell_fixture"]],
            tool_choice={"type": "function", "function": {"name": "shell_fixture"}},
            skills=["safe-tool-replay"],
            metrics=["tool_calls_valid", "latency_ms", "tokens_per_second_decode"],
            max_tokens=64,
            tags=["agent-profile", "codex", "sandbox", "command"],
            provenance="synthetic_representative",
            risk_level="low",
            license="MIT",
        )
    ]
