from __future__ import annotations

import json
from dataclasses import dataclass
from typing import Any

from agentblaster.cleanup import CLEANUP_PLAN_SCHEMA_VERSION, RETENTION_CLEANUP_SCHEMA_VERSION
from agentblaster.engine_onboarding import LOCAL_ENGINE_ONBOARDING_SCHEMA_VERSION
from agentblaster.provider_audit import PROVIDER_AUDIT_SCHEMA_VERSION


SCHEMA_REGISTRY_VERSION = "agentblaster.artifact-schema-registry.v1"


@dataclass(frozen=True)
class ArtifactSchema:
    id: str
    title: str
    schema_version: str
    artifact_paths: tuple[str, ...]
    produced_by: tuple[str, ...]
    consumed_by: tuple[str, ...]
    purpose: str
    required_fields: tuple[str, ...]
    publication_safe: bool
    contains_raw_provider_payloads: bool
    contains_secrets: bool
    notes: tuple[str, ...] = ()


ARTIFACT_SCHEMAS: tuple[ArtifactSchema, ...] = (
    ArtifactSchema(
        id="run-manifest",
        title="Run manifest",
        schema_version="RunManifest",
        artifact_paths=("runs/<run-id>/manifest.json",),
        produced_by=("agentblaster run", "dashboard launch"),
        consumed_by=("agentblaster report", "agentblaster verify", "dashboard", "publication-bundle"),
        purpose="Identity, environment, provider, model, suite hash, retention, and metadata for a run.",
        required_fields=("run_id", "suite", "provider", "contract", "model", "created_at", "case_count"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
    ),
    ArtifactSchema(
        id="suite-snapshot",
        title="Effective suite snapshot",
        schema_version="SuiteDefinition",
        artifact_paths=("runs/<run-id>/suite.json",),
        produced_by=("agentblaster run", "dashboard launch"),
        consumed_by=("agentblaster verify", "publication-bundle", "reviewers"),
        purpose="Canonical parsed suite definition used for the run.",
        required_fields=("name", "description", "cases"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=("May contain benchmark prompts and tool schemas; classify according to suite provenance.",),
    ),
    ArtifactSchema(
        id="suite-audit",
        title="Static suite governance audit",
        schema_version="agentblaster.suite-audit.v1",
        artifact_paths=("reports/<suite>-suite-audit.json", "evidence/*/suite-audit.json"),
        produced_by=("agentblaster suite-audit", "agentblaster evidence bundle"),
        consumed_by=("policy review", "campaign preflight", "release qualification", "media/corporate review"),
        purpose="Static provenance, risk, capability-surface, and dataset-hygiene audit for benchmark suites before provider dispatch.",
        required_fields=("suite", "total_cases", "provenance_counts", "risk_counts", "capability_surfaces", "dataset_hygiene", "findings"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Duplicate workload fingerprints are hashes over benchmark-shaping fields and do not include raw prompt text in findings.",
            "Suite audits are no-dispatch and do not resolve provider secrets or execute tools.",
        ),
    ),
    ArtifactSchema(
        id="normalized-results",
        title="Normalized result rows",
        schema_version="BenchmarkResult",
        artifact_paths=("runs/<run-id>/results.jsonl",),
        produced_by=("agentblaster run", "dashboard launch"),
        consumed_by=("agentblaster report", "agentblaster export", "matrix scorecard", "dashboard"),
        purpose="One normalized per-case result record per line.",
        required_fields=("run_id", "case_id", "suite", "provider", "contract", "model", "ok"),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Excluded from publication bundles by default because it can include detailed failure messages and case metadata.",
            "Successful result rows include normalized telemetry values plus telemetry source, quality, comparison-readiness, and missing-field provenance.",
            "Agent correctness fields include structured-output validity, bounded tool-loop metadata, cancellation metadata, and judge-rubric verdict validity.",
        ),
    ),
    ArtifactSchema(
        id="run-summary",
        title="Run summary",
        schema_version="RunSummary",
        artifact_paths=("runs/<run-id>/summary.json",),
        produced_by=("agentblaster run",),
        consumed_by=("agentblaster report", "matrix summary", "dashboard", "publication-bundle"),
        purpose="Aggregate pass/fail and timing summary for one run.",
        required_fields=("run_id", "suite", "provider", "model", "total_cases", "passed", "failed"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
    ),
    ArtifactSchema(
        id="lifecycle-events",
        title="Run lifecycle events",
        schema_version="agentblaster-run-event-v1",
        artifact_paths=("runs/<run-id>/events.jsonl",),
        produced_by=("agentblaster run", "dashboard launch"),
        consumed_by=("dashboard /api/runs/<run-id>/events", "operator audits"),
        purpose="Redacted operational timeline for run and case completion events.",
        required_fields=("schema", "event", "timestamp", "run_id", "suite", "provider", "contract", "model"),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=("Operational metadata only; not included in publication bundles by default.",),
    ),
    ArtifactSchema(
        id="cleanup-plan",
        title="Manual cleanup plan or execution report",
        schema_version=CLEANUP_PLAN_SCHEMA_VERSION,
        artifact_paths=("reports/manual-cleanup-plan.json", "reports/manual-cleanup-execution.json"),
        produced_by=("agentblaster cleanup --output-json", "agentblaster cleanup --execute --output-json"),
        consumed_by=("operator audits", "enterprise retention review", "CI governance"),
        purpose="Schema-versioned operator cleanup plan or execution result for selected generated run artifacts.",
        required_fields=("schema_version", "report_type", "generated_at", "run_dir", "execute", "selectors", "action_count", "paths", "security"),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not include raw provider payloads, API keys, prompts, response text, or keyring values.",
            "Manual cleanup defaults to dry-run planning; deletion requires explicit --execute.",
            "Direct cleanup reports include local paths; route them through evidence indexes for publication-safe compact summaries.",
        ),
    ),
    ArtifactSchema(
        id="retention-cleanup",
        title="Retention cleanup plan or execution report",
        schema_version=RETENTION_CLEANUP_SCHEMA_VERSION,
        artifact_paths=("reports/cleanup-plan.json", "reports/retention-cleanup-execution.json"),
        produced_by=("agentblaster cleanup-expired --output-json", "agentblaster cleanup-expired --execute --output-json"),
        consumed_by=("operator audits", "enterprise retention review", "CI governance"),
        purpose="Schema-versioned retention cleanup plan or execution result derived from run manifest retention policy metadata.",
        required_fields=("schema_version", "report_type", "generated_at", "runs_dir", "execute", "action_count", "actions", "security"),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Actions contain retention metadata, action type, selected run directory, expiration time, and removed paths only.",
            "Retention cleanup defaults to dry-run planning; deletion requires explicit --execute.",
            "Direct retention cleanup reports include local paths; route them through evidence indexes for publication-safe compact summaries.",
        ),
    ),
    ArtifactSchema(
        id="redaction-scan",
        title="Redaction scan report",
        schema_version="agentblaster.redaction-scan.v1",
        artifact_paths=("reports/redaction-scan.json", "reports/publication-redaction-scan.json"),
        produced_by=("agentblaster security scan",),
        consumed_by=("claim readiness", "release qualification", "publication approval", "CI governance"),
        purpose="Deterministic local scan report for common secret-like values, local-path leaks, and unsafe ZIP member names in shareable artifacts.",
        required_fields=("schema_version", "ok", "total_paths", "scanned_items", "skipped_items", "findings", "security_notes"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Findings report pattern names, redacted locations, and line numbers only; matched values are never copied.",
            "ZIP bundles are scanned without extraction, including text entries and unsafe or sensitive member names.",
            "This is a deterministic release gate, not a complete DLP or vulnerability scanner.",
        ),
    ),
    ArtifactSchema(
        id="provider-audit",
        title="Redacted provider and auth posture audit",
        schema_version=PROVIDER_AUDIT_SCHEMA_VERSION,
        artifact_paths=("reports/provider-audit.json", "evidence/*/provider-audit.json"),
        produced_by=("agentblaster providers audit", "agentblaster evidence bundle --include-provider-audit"),
        consumed_by=(
            "policy review",
            "benchmark readiness",
            "campaign preflight",
            "release qualification",
            "claim readiness",
            "evidence index",
            "dashboard setup-status",
            "dashboard review artifacts",
            "corporate security review",
        ),
        purpose="Static provider inventory and policy audit covering remote flags, endpoint hosts, TLS posture, cost/rate-limit readiness, declared capabilities, optional keyring availability, and redacted API-key reference posture.",
        required_fields=(
            "schema_version",
            "total_providers",
            "remote_providers",
            "policy_controls",
            "secret_backend_posture",
            "providers",
            "security_notes",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not contact endpoints, resolve secrets, read environment variables, inspect keyring values, or read dotenv secret files.",
            "Secret references are summarized by backend kind and booleans only; raw secret names, paths, and values are excluded.",
            "secret_backend_posture records static backend support and keyring dependency availability without reading keyring entries.",
            "Writable keyring/dotenv backends are flagged so operators can confirm policy-guarded pre-write setup was used before storing API-key material.",
            "Release qualification, claim-readiness, evidence-index, and dashboard consumers copy compact counts, finding codes, auth-backend posture, and secret-backend posture only.",
        ),
    ),
    ArtifactSchema(
        id="raw-response",
        title="Raw response artifact",
        schema_version="provider-native",
        artifact_paths=("runs/<run-id>/raw/<case-id>.response.json",),
        produced_by=("agentblaster run --raw-traces redacted", "agentblaster run --raw-traces full"),
        consumed_by=("debug/replay workflows",),
        purpose="Provider response payload for controlled debugging or replay.",
        required_fields=(),
        publication_safe=False,
        contains_raw_provider_payloads=True,
        contains_secrets=False,
        notes=("Full raw traces require explicit policy permission. Publication bundles exclude raw traces.",),
    ),
    ArtifactSchema(
        id="integrity-manifest",
        title="Integrity manifest",
        schema_version="RunIntegrityManifest",
        artifact_paths=("runs/<run-id>/integrity.json",),
        produced_by=("agentblaster run",),
        consumed_by=("agentblaster verify", "publication-bundle", "signature verification"),
        purpose="SHA-256 manifest for run artifacts.",
        required_fields=("run_id", "created_at", "artifacts"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
    ),
    ArtifactSchema(
        id="selftest-report",
        title="AgentBlaster selftest report",
        schema_version="agentblaster.selftest-report.v1",
        artifact_paths=("test-reports/selftest/<run-id>/selftest-report.json", "test-reports/selftest/<run-id>/selftest.json"),
        produced_by=("agentblaster selftest", "agentblaster selftest report"),
        consumed_by=("release qualification", "claim readiness", "evidence index", "SDLC reviewers"),
        purpose="Compact execution evidence for AgentBlaster's own SDLC test harness tiers.",
        required_fields=("schema_version", "run_id", "tier", "marker_expression", "started_at", "completed_at", "duration_ms", "exit_code", "ok"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Release summaries copy only tier, status, exit code, duration, browser metadata, and JUnit presence.",
            "Command strings, environment maps, and raw test output are not copied into release qualification review summaries.",
        ),
    ),
    ArtifactSchema(
        id="sdlc-validation-manifest",
        title="AgentBlaster SDLC validation manifest",
        schema_version="agentblaster.sdlc-validation-manifest.v1",
        artifact_paths=("test-reports/selftest/sdlc-validation-manifest.json", "reports/sdlc-validation-manifest.json"),
        produced_by=("agentblaster quality validation-manifest",),
        consumed_by=(
            "release qualification",
            "claim readiness via release bundle",
            "evidence index",
            "dashboard review artifacts",
            "operator handoff",
            "CI governance",
            "SDLC reviewers",
            "corporate review",
        ),
        purpose="Static no-execution manifest that ties AgentBlaster selftest tiers, SDLC gates, Chrome/Codex GUI evidence hooks, and release evidence expectations into one reviewable artifact.",
        required_fields=("schema_version", "name", "scope", "boundary", "summary", "tiers", "gates", "gui", "release_evidence", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Generating the manifest does not run tests, resolve secrets, contact providers, or open the dashboard.",
            "Chrome/Codex evidence hooks require redacted fixtures and must not expose real API keys, raw traces, or browser history.",
            "Use selftest-report artifacts for execution proof; this manifest is planning and review evidence.",
            "Release qualification, evidence-index, claim-readiness, and dashboard consumers copy compact manifest summaries only.",
        ),
    ),
    ArtifactSchema(
        id="benchmark-readiness",
        title="Benchmark readiness dossier",
        schema_version="agentblaster.benchmark-readiness.v1",
        artifact_paths=("reports/<provider>-<suite>-readiness.json",),
        produced_by=("agentblaster providers readiness",),
        consumed_by=("campaign preflight", "release qualification", "claim readiness", "evidence index", "dashboard review artifacts", "operator handoff"),
        purpose="No-network preflight dossier for one provider, suite, and model target, including policy posture, suite capability compatibility, contract-check planning, metric coverage, redacted provider-auth posture, and static secret-backend posture.",
        required_fields=("schema_version", "provider", "suite", "model", "ready", "summary", "provider_auth_posture", "secret_backend_posture"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not contact endpoints, resolve API keys, inspect keyring values, or read raw traces.",
            "Provider-auth posture is copied by backend kind and booleans only; raw secret values and full secret reference names are excluded from release and dashboard summaries.",
            "secret_backend_posture carries static keyring dependency availability and recommended enterprise backend metadata without reading keyring values.",
        ),
    ),
    ArtifactSchema(
        id="benchmark-readiness-input-list",
        title="Benchmark readiness input list",
        schema_version="agentblaster.benchmark-readiness-input-list.v1",
        artifact_paths=("campaigns/<name>/reports/benchmark-readiness-inputs.txt",),
        produced_by=("agentblaster models campaign-plan",),
        consumed_by=("agentblaster evidence campaign-preflight --benchmark-readiness-list", "operator handoff"),
        purpose="Line-delimited list of generated benchmark-readiness dossier paths for large campaign preflight bundles.",
        required_fields=("one readiness dossier path per non-comment line",),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "The list stores paths to readiness dossiers only, not provider configs, API keys, prompts, traces, or provider payloads.",
            "Blank lines and comment lines starting with # are ignored by campaign preflight.",
        ),
    ),
    ArtifactSchema(
        id="provider-contract-check",
        title="Provider contract check",
        schema_version="agentblaster.provider-contract-check.v1",
        artifact_paths=("reports/<provider>-contract-check.json",),
        produced_by=("agentblaster providers contract-check --execute",),
        consumed_by=("release qualification", "claim readiness", "provider onboarding", "engine advisory"),
        purpose="Executed OpenAI/Responses/Anthropic-compatible endpoint conformance check for model listing, chat, streaming, structured output, tool calling, Responses stateful continuation, and capability-evidence coverage disclosure.",
        required_fields=(
            "schema_version",
            "ok",
            "mode",
            "provider",
            "model",
            "contract_surface",
            "checks",
            "capability_evidence",
            "summary",
            "safety",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Plan-only contract-check artifacts have ok=false and are not sufficient for publication claim readiness.",
            "Execution contacts the configured provider but stores only compact redacted check status and messages.",
            "The nested contract_surface object documents endpoint paths, auth scheme, request features, and response evidence without raw provider payloads.",
            "Capability evidence distinguishes direct probes, proxy coverage such as judge_rubric through structured_output, and capabilities such as prompt_caching or tool_parser_repair that require separate benchmark evidence.",
        ),
    ),
    ArtifactSchema(
        id="provider-contract-surface",
        title="Provider contract surface",
        schema_version="agentblaster.provider-contract-surface.v1",
        artifact_paths=("reports/<provider>-contract-check.json!/contract_surface", "reports/<matrix>-provider-contract-matrix.json!/contract_surfaces"),
        produced_by=("agentblaster providers contract-check", "agentblaster matrix contract-checks"),
        consumed_by=("release qualification", "claim readiness", "provider onboarding", "engine advisory", "corporate review"),
        purpose="Nested redaction-safe API surface description for OpenAI Chat Completions, OpenAI Responses, and Anthropic Messages compatibility checks.",
        required_fields=("schema_version", "contract", "adapter_family", "transport", "auth", "endpoints", "request_features", "response_evidence"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Records auth scheme and header names only; API-key values and full secret references are never copied.",
            "Endpoint paths and request/response feature names make compatibility claims reviewable across local and internet-facing providers.",
        ),
    ),
    ArtifactSchema(
        id="provider-contract-matrix",
        title="Provider contract-check matrix",
        schema_version="agentblaster.provider-contract-matrix.v1",
        artifact_paths=("reports/<matrix>-provider-contract-matrix.json",),
        produced_by=("agentblaster matrix contract-checks --execute",),
        consumed_by=("release qualification", "claim readiness", "provider onboarding", "matrix preflight"),
        purpose="Campaign-level contract-check artifact covering every unique provider/model target referenced by a benchmark matrix.",
        required_fields=("schema_version", "ok", "mode", "matrix", "summary", "contract_surfaces", "entries", "safety"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Plan-only matrix artifacts have ok=false and are not sufficient for publication claim readiness.",
            "Executed matrix artifacts preserve compact check status without raw provider payloads or secrets.",
            "contract_surfaces summarizes the distinct API surfaces represented by matrix entries.",
        ),
    ),
    ArtifactSchema(
        id="matrix-execution-summary",
        title="Matrix execution summary",
        schema_version="MatrixExecutionSummary",
        artifact_paths=("reports/<matrix>-summary.json",),
        produced_by=("agentblaster run --matrix --matrix-summary-json",),
        consumed_by=(
            "agentblaster matrix report",
            "agentblaster matrix gate",
            "agentblaster matrix scorecard",
            "agentblaster matrix saturation-report",
        ),
        purpose="One index of attempted, completed, and failed matrix entries, including compact engine-target metadata when known.",
        required_fields=("matrix_name", "created_at", "total_runs", "attempted_runs", "completed_runs", "failed_runs", "runs"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Run rows can carry compact engine_target IDs and primary scoring contracts copied from executed run manifests.",
            "The summary stores artifact paths and aggregate counts only; raw provider payloads and raw traces remain outside the matrix summary.",
        ),
    ),
    ArtifactSchema(
        id="matrix-gate",
        title="Matrix gate report",
        schema_version="agentblaster.matrix-gate.v1",
        artifact_paths=("reports/<matrix>-gate.json",),
        produced_by=("agentblaster matrix gate",),
        consumed_by=("CI gates", "release qualification", "claim readiness", "corporate review"),
        purpose="Matrix-level pass/fail threshold report for run completion, case pass rate, failed cases, optional failure-class limits, optional tool-loop stop-reason limits, optional judge-rubric verdict-validity limits, and optional tool-parser repair limits.",
        required_fields=(
            "schema_version",
            "matrix_name",
            "ok",
            "total_runs",
            "attempted_runs",
            "completed_runs",
            "failed_runs",
            "pass_rate_percent",
            "thresholds",
            "failure_class_summary",
            "failure_class_artifacts_missing",
            "tool_loop_stop_summary",
            "tool_loop_artifacts_missing",
            "judge_rubric_cases",
            "judge_verdicts_valid",
            "judge_verdict_valid_rate_percent",
            "judge_verdict_artifacts_missing",
            "invalid_tool_call_count",
            "tool_parser_repair_cases",
            "tool_parser_repairs_valid",
            "tool_parser_repair_valid_rate_percent",
            "tool_parser_repair_artifacts_missing",
            "findings",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Failure-class summaries and thresholds read normalized results.jsonl artifacts referenced by the matrix summary.",
            "Tool-loop, judge-rubric, and tool-parser repair summaries read only compact normalized result fields, never prompt text, tool arguments, or raw provider payloads.",
            "Summary-only loading records missing/unreadable referenced result artifacts without failing the gate; failure-class, tool-loop, judge-rubric, and tool-parser repair thresholds treat them as blocking evidence gaps.",
            "The report records aggregate counts only and excludes raw traces, provider payloads, provider configs, and secrets.",
        ),
    ),
    ArtifactSchema(
        id="matrix-pressure-audit",
        title="Matrix pressure audit",
        schema_version="agentblaster.matrix-pressure-audit.v1",
        artifact_paths=("reports/<matrix>-pressure-audit.json",),
        produced_by=("agentblaster matrix pressure-audit",),
        consumed_by=("campaign preflight", "operator handoff", "engine comparison planning"),
        purpose="Static prompt, prefill, static-prefix, output-budget, and concurrency pressure inventory for benchmark matrices.",
        required_fields=("schema_version", "matrix", "totals", "runs"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=("Does not dispatch provider requests or inspect run artifacts.",),
    ),
    ArtifactSchema(
        id="matrix-report",
        title="Matrix report",
        schema_version="agentblaster-matrix-report-v1",
        artifact_paths=(
            "reports/<matrix>-matrix-report.json",
            "reports/<matrix>-matrix-report.html",
            "reports/<matrix>-matrix-report.md",
            "reports/<matrix>-matrix-report.pdf",
        ),
        produced_by=("agentblaster matrix report",),
        consumed_by=("media/corporate reporting", "campaign retrospectives", "release qualification"),
        purpose="Publication-oriented matrix audit report with aggregate provider/model summaries, run-entry statuses, and PDF/HTML/Markdown/JSON outputs.",
        required_fields=("report_type", "matrix", "scorecard", "provider_summary", "model_summary", "runs", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=("Reads matrix execution summaries only; raw traces and provider payloads are not inspected.",),
    ),
    ArtifactSchema(
        id="matrix-saturation-report",
        title="Matrix saturation report",
        schema_version="agentblaster.matrix-saturation.v1",
        artifact_paths=("reports/<matrix>-matrix-saturation.json",),
        produced_by=("agentblaster matrix saturation-report",),
        consumed_by=("engine advisory", "operator handoff", "media/corporate review"),
        purpose="Executed-result concurrency analysis for latency, TTFT, queueing, rate-limit wait, decode throughput, and pass-rate changes across matrix concurrency levels.",
        required_fields=("schema_version", "ok", "matrix", "summary", "concurrency_evidence", "groups", "findings"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads normalized matrix summaries and result rows only; raw traces and provider payloads are not inspected.",
            "concurrency_evidence provides compact multi-level concurrency coverage, queue pressure, rate-limit wait, and top pressure entries for review.",
        ),
    ),
    ArtifactSchema(
        id="matrix-scorecard",
        title="Matrix scorecard",
        schema_version="agentblaster-matrix-scorecard-v1",
        artifact_paths=(
            "reports/<matrix>-matrix-scorecard.json",
            "reports/<matrix>-matrix-scorecard.html",
            "reports/<matrix>-matrix-scorecard.md",
            "reports/<matrix>-matrix-scorecard.svg",
            "reports/<matrix>-matrix-scorecard.png",
            "reports/<matrix>-matrix-scorecard.pdf",
        ),
        produced_by=("agentblaster matrix scorecard",),
        consumed_by=("media/corporate reporting", "campaign retrospectives", "engine roadmaps"),
        purpose="Publication-oriented matrix leaderboard with normalized per-entry metrics, telemetry quality/readiness summaries, stats-comparability summaries, compact concurrency evidence, tool-loop stop-reason counts, judge-rubric verdict-validity counts, and architecture and quantization rollups for model-family comparisons.",
        required_fields=(
            "report_type",
            "matrix",
            "scorecard",
            "architecture_summary",
            "quantization_summary",
            "leaderboard",
            "entries",
            "security",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads normalized result rows and run manifests when available; raw traces and provider payloads are not inspected.",
            "scorecard parser-repair fields, telemetry_quality_summary, stats_comparability_summary, and concurrency_evidence provide compact publication-review evidence without copying raw rows.",
        ),
    ),
    ArtifactSchema(
        id="matrix-publication-bundle",
        title="Matrix publication bundle",
        schema_version="agentblaster-matrix-publication.zip",
        artifact_paths=("publication-bundles/<matrix>.agentblaster-matrix-publication.zip",),
        produced_by=("agentblaster matrix publication-bundle",),
        consumed_by=("media/corporate reporting", "release qualification", "claim readiness", "evidence index", "dashboard review artifacts", "publication approval"),
        purpose="Deterministic zip containing only matrix summary, matrix report, and matrix scorecard artifacts for external review.",
        required_fields=("matrix-publication-bundle-manifest.json", "<matrix>-summary.json", "<matrix>-matrix-scorecard.json"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Excludes per-run results.jsonl, raw traces, provider payloads, exports, API keys, and request headers.",
            "The generated matrix-publication-bundle-manifest.json records compact engine-target IDs plus asset roles for media, executive, corporate-review, and automation consumers.",
        ),
    ),
    ArtifactSchema(
        id="matrix-publication-bundle-manifest",
        title="Matrix publication bundle manifest",
        schema_version="agentblaster.matrix-publication-bundle.v1",
        artifact_paths=("publication-bundles/<matrix>.agentblaster-matrix-publication.zip!/matrix-publication-bundle-manifest.json",),
        produced_by=("agentblaster matrix publication-bundle",),
        consumed_by=("media/corporate reporting", "release qualification", "claim readiness", "evidence index", "publication approval", "dashboard review artifacts"),
        purpose="Generated metadata inside a matrix publication bundle covering packaged matrix artifacts, compact engine-target IDs, architecture/quantization rollups, media-kit roles, and security boundaries.",
        required_fields=("schema_version", "matrix", "artifact_count", "artifacts", "media_kit", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "The media_kit block uses agentblaster.media-kit.v1 and maps scorecard JSON/PDF/SVG/PNG assets to professional publication roles.",
            "Security flags explicitly state that per-run result rows, raw traces, provider payloads, API keys, and request headers are excluded.",
        ),
    ),
    ArtifactSchema(
        id="publication-bundle",
        title="Run publication bundle",
        schema_version="agentblaster.publication-bundle.zip",
        artifact_paths=("publication-bundles/<run-id>.agentblaster-publication.zip",),
        produced_by=("agentblaster publication-bundle",),
        consumed_by=("media/corporate reporting", "release qualification", "claim readiness", "publication approval"),
        purpose="Deterministic zip containing only allowlisted run-level publication artifacts and generated bundle metadata.",
        required_fields=("publication-bundle-manifest.json", "publication.json", "summary.json", "integrity.json"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Excludes results.jsonl, raw traces, provider payloads, exports, caches, API keys, and request headers.",
            "The generated publication-bundle-manifest.json is not a run artifact; it summarizes packaged artifact names and publication readiness.",
            "When signature.json is present, bundle creation requires it to match integrity.json and the bundle manifest records compact signature coverage metadata.",
        ),
    ),
    ArtifactSchema(
        id="publication-bundle-manifest",
        title="Run publication bundle manifest",
        schema_version="agentblaster.publication-bundle.v1",
        artifact_paths=("publication-bundles/<run-id>.agentblaster-publication.zip!/publication-bundle-manifest.json",),
        produced_by=("agentblaster publication-bundle",),
        consumed_by=("media/corporate reporting", "release qualification", "claim readiness", "publication approval"),
        purpose="Generated metadata inside a run publication bundle covering packaged artifacts, media-kit roles, publication readiness, integrity/signature coverage, and security boundaries.",
        required_fields=("schema_version", "run_id", "artifact_count", "artifacts", "media_kit", "publication_readiness", "integrity", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Derived from allowlisted publication artifacts only.",
            "The media_kit block uses agentblaster.media-kit.v1 and maps JSON/PDF/HTML/Markdown/SVG/PNG assets to professional publication roles.",
            "Security flags explicitly state that raw provider payloads, API keys, request headers, exports, caches, and results.jsonl are excluded.",
        ),
    ),
    ArtifactSchema(
        id="release-provenance",
        title="Release provenance",
        schema_version="agentblaster.release-provenance",
        artifact_paths=("reports/release-provenance.json",),
        produced_by=("agentblaster release provenance",),
        consumed_by=("release qualification", "claim readiness", "CI governance", "media/corporate review"),
        purpose="Static release metadata, runtime/package inventory, packaging readiness, source hashes, and SBOM evidence for release governance.",
        required_fields=(
            "schema",
            "schema_version",
            "generated_at",
            "project",
            "runtime",
            "dependencies",
            "sbom",
            "packaging_readiness",
            "source_hashes",
            "security_notes",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not read provider configs, environment variables, keyrings, run traces, raw responses, or dashboard state.",
            "Installed package inventory is optional and generated from importlib metadata only when explicitly requested.",
            "Vulnerability status must come from a dedicated scanner; release provenance is an inventory and readiness artifact.",
        ),
    ),
    ArtifactSchema(
        id="release-sbom",
        title="Release SPDX-lite SBOM",
        schema_version="agentblaster.sbom.v1",
        artifact_paths=("reports/release-provenance.json!/sbom",),
        produced_by=("agentblaster release provenance",),
        consumed_by=("release qualification", "CI governance", "supply-chain review", "media/corporate review"),
        purpose="Redaction-safe SPDX-lite package inventory derived from pyproject declarations plus optional installed-package metadata.",
        required_fields=("schema_version", "format", "root_package", "packages", "relationships", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Includes dependency specifiers and package names, not environment variables or credential material.",
            "Does not contact package indexes or perform vulnerability/license legal analysis.",
            "Security flags indicate whether optional installed-package inventory was included.",
        ),
    ),
    ArtifactSchema(
        id="publication-report",
        title="Publication report",
        schema_version="agentblaster.publication.v1",
        artifact_paths=("runs/<run-id>/publication.json", "runs/<run-id>/report-card.svg", "runs/<run-id>/report-card.png", "runs/<run-id>/report.pdf"),
        produced_by=("agentblaster report --format publication,card,png",),
        consumed_by=("publication-bundle", "media/corporate reporting"),
        purpose="Shareable structured and visual summaries for benchmark claims.",
        required_fields=("run", "scorecard", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
    ),
    ArtifactSchema(
        id="publication-brief",
        title="Publication brief",
        schema_version="agentblaster.publication-brief.v1",
        artifact_paths=("reports/<claim>-publication-brief.json", "reports/<claim>-publication-brief.md"),
        produced_by=("agentblaster release publication-brief",),
        consumed_by=(
            "release qualification",
            "claim readiness via release bundle",
            "evidence index",
            "dashboard review artifacts",
            "media/corporate reporting",
            "executive review",
            "release signoff",
        ),
        purpose="Redaction-safe executive brief that summarizes claim readiness, compact engine-target IDs, scorecards, protocol-repair posture, media-kit readiness, disclosures, and recommended publication language without raw benchmark rows.",
        required_fields=("schema_version", "name", "ready", "claim_readiness", "protocol_repair_summary", "media_kit", "proof_points", "disclosures", "recommended_language", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads compact review artifacts only, such as claim-readiness and matrix-scorecard JSON, including compact engine-target and parser-repair summaries.",
            "Media-kit readiness is summarized from compact claim-readiness evidence and does not open publication ZIP bundles.",
            "Does not open results.jsonl, raw traces, provider configs, keyrings, dotenv files, or remote endpoints.",
            "Blockers and warnings are rendered as disclosures rather than hidden from publication materials.",
            "Release qualification, evidence-index, claim-readiness, and dashboard consumers copy compact brief summaries only.",
        ),
    ),
    ArtifactSchema(
        id="protocol-repair-posture",
        title="Protocol repair posture",
        schema_version="agentblaster.protocol-repair-posture.v1",
        artifact_paths=("reports/<claim>-protocol-repair.json", "reports/<claim>-protocol-repair.md"),
        produced_by=("agentblaster release protocol-repair",),
        consumed_by=(
            "release qualification",
            "claim readiness",
            "evidence index",
            "dashboard review artifacts",
            "media/corporate reporting",
            "engine roadmaps",
        ),
        purpose="Redaction-safe standalone posture report for invalid tool-call emissions and tool-parser repair validity across compact matrix scorecard and matrix-gate evidence.",
        required_fields=(
            "schema_version",
            "name",
            "status",
            "ready",
            "scorecard_summary",
            "matrix_gate_summary",
            "scorecards",
            "matrix_gates",
            "disclosures",
            "recommendations",
            "security",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads compact claim-readiness, matrix-scorecard, and matrix-gate JSON artifacts only.",
            "Does not open results.jsonl, raw traces, provider configs, keyrings, dotenv files, or remote endpoints.",
            "Direct matrix scorecards and matrix gates take precedence over compact claim-readiness copies to avoid double-counting.",
            "The report is intended for protocol-repair signoff, engine roadmaps, and publication disclosures.",
        ),
    ),
    ArtifactSchema(
        id="workflow-readiness",
        title="Workflow readiness report",
        schema_version="agentblaster.workflow-readiness.v1",
        artifact_paths=("reports/<campaign>-workflow-readiness.json", "reports/<campaign>-workflow-readiness.md"),
        produced_by=("agentblaster release workflow-readiness",),
        consumed_by=(
            "campaign preflight",
            "release qualification",
            "claim readiness",
            "evidence index",
            "dashboard review artifacts",
            "media/corporate reporting",
            "engine roadmaps",
        ),
        purpose="No-dispatch campaign coverage signoff for agentic workflow surfaces such as concurrency, prefill/cache pressure, tool calling, tool loops, structured output, MCP, LCP, skills, cancellation, trace replay, judge rubrics, and harness engineering.",
        required_fields=(
            "schema_version",
            "name",
            "status",
            "ready",
            "required_surfaces",
            "summary",
            "coverage",
            "gaps",
            "suite_sources",
            "matrix_pressure_audits",
            "harness_reviews",
            "recommendations",
            "security",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads suite definitions, matrix definitions, matrix pressure audits, and harness-review artifacts without dispatching providers.",
            "Does not open results.jsonl, raw traces, provider configs, keyrings, dotenv files, remote endpoints, or raw provider payloads.",
            "Prompts and tool arguments are not copied into the report; coverage is represented by aggregate surface counts only.",
            "Use before expensive benchmark execution to prove intended agentic workflow coverage.",
        ),
    ),
    ArtifactSchema(
        id="security-posture",
        title="Enterprise security posture report",
        schema_version="agentblaster.security-posture.v1",
        artifact_paths=("reports/security-posture.json", "reports/security-posture.md"),
        produced_by=("agentblaster security posture",),
        consumed_by=(
            "corporate security review",
            "release signoff",
            "publication approval",
            "operator handoff",
            "CI governance",
        ),
        purpose="Static enterprise/corporate security posture artifact that consolidates policy controls, optional keyring posture, provider audit summaries, redaction scan status, and review-artifact security flags without resolving secrets.",
        required_fields=(
            "schema_version",
            "name",
            "status",
            "ready",
            "summary",
            "policy",
            "secret_backend_posture",
            "provider_audits",
            "redaction_scans",
            "review_artifacts",
            "findings",
            "recommendations",
            "security",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not dispatch providers, resolve API keys, read keyring values, inspect environment variable values, or contact endpoints.",
            "Provider audit inputs summarize secret reference kinds only; raw secret names and values are excluded.",
            "Redaction scan inputs copy finding pattern names and locations only, not matched values.",
            "Review artifact inputs are summarized by schema and boolean security flags only.",
            "Apple Keychain/keyring support is treated as optional; environment references remain the portable enterprise baseline.",
        ),
    ),
    ArtifactSchema(
        id="readiness-artifacts",
        title="Static readiness artifacts",
        schema_version="various",
        artifact_paths=("reports/environment-readiness.json", "reports/packaging-readiness.json", "reports/implementation-status.json"),
        produced_by=("agentblaster doctor", "agentblaster release packaging-readiness", "agentblaster implementation-status"),
        consumed_by=("release qualification", "operator handoff", "CI governance"),
        purpose="No-dispatch readiness, implementation inventory, and requirement-coverage handoff artifacts.",
        required_fields=("schema_version",),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Direct readiness artifacts can include local project, output, package, or file-evidence paths for operator handoff.",
            "Use release qualification bundles, evidence indexes, dashboard summaries, or explicit redaction review before external publication.",
        ),
    ),
    ArtifactSchema(
        id="enterprise-policy-template",
        title="Enterprise policy template",
        schema_version="agentblaster.enterprise-policy-template.v1",
        artifact_paths=("agentblaster.policy.yaml", "reports/enterprise-policy-template.json"),
        produced_by=("agentblaster policy template",),
        consumed_by=("operator handoff", "security review", "CI governance", "corporate review"),
        purpose="Strict no-secret enterprise baseline for local-only or approved remote-gateway benchmark policies.",
        required_fields=("schema_version", "profile", "policy", "review_notes"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "The YAML template contains only control values and approved reference prefixes, not API-key values.",
            "Dotenv plaintext fallback is excluded from the enterprise baseline.",
            "Remote-gateway templates require API-key references, cost models, rate limits, TLS, and approved hosts.",
        ),
    ),
    ArtifactSchema(
        id="policy-control-summary",
        title="Policy control summary",
        schema_version="agentblaster.policy-control-summary.v1",
        artifact_paths=("reports/policy-control-summary.json",),
        produced_by=("agentblaster policy controls",),
        consumed_by=("operator handoff", "security review", "CI governance", "corporate review"),
        purpose="Compact review artifact summarizing enterprise security posture of a policy file without resolving secrets or contacting providers.",
        required_fields=("schema_version", "name", "enterprise_ready", "summary", "controls", "blockers", "warnings", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reports control posture only; it does not validate live providers or secret availability.",
            "Unsafe exceptions such as full raw traces, insecure TLS, non-loopback HTTP, and plaintext dotenv secret backends are surfaced as blockers.",
        ),
    ),
    ArtifactSchema(
        id="implementation-status",
        title="Implementation status inventory",
        schema_version="agentblaster.implementation-status.v1",
        artifact_paths=("reports/implementation-status.json", "readiness/implementation-status.json"),
        produced_by=("agentblaster implementation-status", "agentblaster evidence campaign-preflight"),
        consumed_by=("operator handoff", "release qualification", "claim readiness", "evidence index", "dashboard review artifacts", "CI governance", "campaign preflight"),
        purpose="Static implementation and requirement-coverage inventory for code/docs/test surfaces, built-in suites, harness-engineering cases, stats comparability, enterprise controls, publication governance, and SDLC gates.",
        required_fields=(
            "schema_version",
            "status",
            "implemented_areas",
            "partial_areas",
            "missing_areas",
            "areas",
            "suite_inventory",
            "requirements_inventory",
            "validation",
            "security_notes",
        ),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Static file-presence and catalog inventory only; it does not run tests, contact providers, resolve secrets, inspect keyring values, or read dotenv secret files.",
            "Raw reports can include local project-root and file evidence paths; release qualification bundles redact them, campaign preflight redacts its embedded copy, and evidence/dashboard summaries copy compact status only.",
            "requirements_inventory includes target engines, engine-target standardization metadata, provider contracts, Qwen/Gemma model targets, agent profiles, harness-engineering suite/profile coverage, stats-comparability/metric-coverage catalogs, enterprise controls, publication governance, and selftest gates.",
        ),
    ),
    ArtifactSchema(
        id="harness-review",
        title="Harness suite review",
        schema_version="agentblaster.harness-review.v1",
        artifact_paths=("reports/<suite>-harness-review.json",),
        produced_by=("agentblaster harness review",),
        consumed_by=("suite calibration", "release qualification", "operator handoff"),
        purpose="Static generated-suite review artifact covering provenance, capability surfaces, assertions, metrics, risks, mixed emerging-workflow surfaces, and calibration requirements.",
        required_fields=("schema_version", "suite", "provenance", "generated", "surface_counts", "assertion_counts", "review", "safety"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not include prompts, provider payloads, raw traces, API keys, or request headers.",
            "Release and dashboard review summaries preserve only compact suite, generator, calibration, surface-count, and assertion-count metadata.",
        ),
    ),
    ArtifactSchema(
        id="suite-calibration-report",
        title="Suite calibration report",
        schema_version="agentblaster.suite-calibration-report.v1",
        artifact_paths=("reports/<suite>-calibration-report.json",),
        produced_by=("agentblaster suite-calibration --calibration",),
        consumed_by=("release qualification", "claim readiness", "operator handoff"),
        purpose="Static release-gate calibration report proving known-good, known-bad, failure-taxonomy, human-review, and approval coverage for generated or synthetic suites.",
        required_fields=("schema_version", "suite", "suite_sha256", "generated", "require_release_gate", "passed", "summary", "findings", "warnings"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not contact providers, read keyrings, or include raw traces.",
            "Failed calibration reports block release qualification when supplied as release-gate evidence.",
        ),
    ),
    ArtifactSchema(
        id="campaign-preflight-bundle",
        title="Campaign preflight bundle",
        schema_version="agentblaster.campaign-preflight-bundle.v1",
        artifact_paths=(
            "campaign-preflight/<name>/manifest.json",
            "campaign-preflight/<name>/matrices/index.json",
            "campaign-preflight/<name>/pressure/*-pressure.json",
            "campaign-preflight/<name>/readiness/benchmark-readiness-index.json",
        ),
        produced_by=("agentblaster evidence campaign-preflight", "agentblaster evidence campaign-preflight --benchmark-readiness-list"),
        consumed_by=("operator handoff", "release qualification", "claim readiness", "dashboard review artifacts", "media/corporate review"),
        purpose="No-dispatch folder of static campaign readiness, benchmark-readiness summaries, policy, provider audit, schema, matrix inventory, and matrix pressure artifacts.",
        required_fields=("schema_version", "matrix_count", "artifact_count", "security"),
        publication_safe=False,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not execute benchmark runs, contact providers, resolve API keys, or read keyring values.",
            "Raw campaign preflight folders can include local output, matrix, policy, and dry-run command paths for operator handoff.",
            "manifest.review_summary is the compact no-local-path summary intended for release qualification, evidence indexes, dashboard review, and claim-readiness checks.",
            "Use release qualification bundles, evidence indexes, dashboard summaries, or explicit redaction review for external publication.",
            "When benchmark-readiness dossiers are supplied directly or through list files, manifest.json points to readiness/benchmark-readiness-index.json for claim readiness and dashboard review.",
        ),
    ),
    ArtifactSchema(
        id="normalized-response-telemetry",
        title="Normalized response telemetry sample",
        schema_version="agentblaster.normalized-telemetry.v1",
        artifact_paths=("reports/<provider>-normalized-telemetry.json",),
        produced_by=("agentblaster catalog normalize-telemetry", "agentblaster run"),
        consumed_by=("metric audits", "engine onboarding", "reporting", "release qualification", "evidence index", "dashboard review artifacts"),
        purpose="Common token, timing, cache, throughput, and finish-reason fields normalized from provider-specific response metadata.",
        required_fields=(
            "schema_version",
            "contract",
            "stats_profile",
            "values",
            "sources",
            "quality",
            "comparison_readiness",
            "stats_comparability",
            "missing",
        ),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Use sample artifacts to validate stats mapping before relying on cross-engine comparisons.",
            "Release qualification, evidence-index, and dashboard summaries copy compact readiness and labeling counts only, not raw_usage, raw_stats, or source maps.",
            "AgentBlaster-measured streaming TTFT takes precedence over provider-reported TTFT aliases in normalized values, while raw_stats preserves provider timing fields.",
            "quality, comparison_readiness, and stats_comparability classify normalized fields as native, measured, inferred, conditional, raw provenance, or missing before cross-engine claims.",
        ),
    ),
    ArtifactSchema(
        id="local-engine-onboarding",
        title="Local engine onboarding checklist",
        schema_version=LOCAL_ENGINE_ONBOARDING_SCHEMA_VERSION,
        artifact_paths=("reports/local-engine-onboarding.json",),
        produced_by=("agentblaster engines onboarding --format json",),
        consumed_by=("operator handoff", "provider onboarding", "dashboard planning", "corporate setup review"),
        purpose="Static local-engine setup checklist joining provider presets, reviewable launch recipes, engine target metadata, workflow surfaces, and telemetry claim policy.",
        required_fields=("schema_version", "model", "model_targets", "engine_count", "engines", "standardization", "safety"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Does not execute commands, start engines, contact endpoints, resolve secrets, or write provider config.",
            "Each engine entry includes the matching engine target, primary scoring contract, telemetry profiles, workflow surfaces, prefill/concurrency challenge classes, and native metric policy.",
        ),
    ),
    ArtifactSchema(
        id="telemetry-audit",
        title="Run telemetry audit",
        schema_version="agentblaster.telemetry-audit.v1",
        artifact_paths=("reports/<run-id>-telemetry-audit.json",),
        produced_by=("agentblaster telemetry-audit",),
        consumed_by=("comparison gates", "release qualification", "media/corporate review"),
        purpose="Per-run audit of normalized telemetry completeness, source provenance, and required metric comparability.",
        required_fields=("schema_version", "run", "summary", "comparison_readiness", "fields", "findings"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads normalized result rows only and does not inspect raw traces or provider configs.",
            "comparison_readiness summarizes native/measured versus inferred/conditional field provenance for publication review.",
        ),
    ),
    ArtifactSchema(
        id="metric-coverage",
        title="Metric coverage",
        schema_version="agentblaster.metric-coverage.v1",
        artifact_paths=("reports/<provider>-metric-coverage.json", "reports/metric-coverage-catalog.json"),
        produced_by=("agentblaster providers metric-coverage",),
        consumed_by=("readiness dossier", "engine advisory", "publication review"),
        purpose="Static normalized metric coverage, claim-contract, and comparability guidance by provider contract or native adapter.",
        required_fields=("schema_version", "provider", "summary", "comparability", "claim_contract", "fields"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Provider-specific reports use agentblaster.metric-coverage.v1; catalog reports use agentblaster.metric-coverage-catalog.v1.",
            "claim_contract classifies metric families as leaderboard-eligible, advisory, limited, or unsupported before publication claims.",
            "Reports are static and do not contact endpoints or resolve API keys.",
        ),
    ),
    ArtifactSchema(
        id="claim-readiness",
        title="Benchmark claim readiness",
        schema_version="agentblaster.claim-readiness.v1",
        artifact_paths=("reports/<claim>-claim-readiness.json",),
        produced_by=("agentblaster release claim-readiness",),
        consumed_by=("release qualification", "media/corporate review", "publication approval"),
        purpose="Static gate that checks whether experiment, gate, audit, matrix scorecard, provenance, redaction, publication, and release evidence is present and passing or reviewable.",
        required_fields=("schema_version", "name", "ready", "summary", "evidence", "checks"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads supplied review artifacts only and does not open raw traces, resolve secrets, or contact providers.",
            "The evidence block preserves compact matrix-gate failure-class, matrix-scorecard architecture/quantization/telemetry/concurrency, harness-review, engine-advisory, evidence-index, suite-audit, and metric-coverage summaries for publication review.",
            "Check paths are reduced to safe artifact names when absolute or parent-relative inputs are supplied.",
        ),
    ),
    ArtifactSchema(
        id="evidence-index",
        title="Review evidence index",
        schema_version="agentblaster.evidence-index.v1",
        artifact_paths=("reports/<claim>-evidence-index.json",),
        produced_by=("agentblaster evidence index",),
        consumed_by=("release qualification", "claim readiness", "media/corporate review", "dashboard review"),
        purpose="Publication-safe compact index over supplied review artifacts, release bundles, matrix gates, harness reviews, engine advisories, and evidence packet readiness.",
        required_fields=("schema_version", "name", "artifact_count", "status_counts", "readiness", "cleanup_evidence", "artifacts", "security"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Reads only supplied compact JSON artifacts and release qualification bundle manifest.json files.",
            "The readiness block classifies packets as ready, review-required, or blocked from compact artifact statuses.",
            "Artifact paths are reduced to safe names when absolute or parent-relative inputs are supplied.",
            "Campaign preflight manifests are summarized from manifest.review_summary without copying local matrix paths or dry-run commands.",
            "Rejects raw traces, event streams, normalized result rows, provider payloads, prompts, responses, API keys, and request headers.",
        ),
    ),
    ArtifactSchema(
        id="engine-improvement-advisory",
        title="Engine improvement advisory",
        schema_version="agentblaster.engine-improvement-advisory.v1",
        artifact_paths=("reports/<engine>-improvement-plan.json",),
        produced_by=("agentblaster engines improvement-plan",),
        consumed_by=("engine roadmaps", "AFM release planning", "benchmark retrospectives", "release qualification", "dashboard review"),
        purpose="Evidence-driven priority plan for improving an engine based on pressure, telemetry, metric coverage claim contracts, gates including parser-repair failures, contract checks, saturation, and harness-review artifacts.",
        required_fields=("schema_version", "engine", "summary", "evidence", "priorities"),
        publication_safe=True,
        contains_raw_provider_payloads=False,
        contains_secrets=False,
        notes=(
            "Consumes redaction-safe review artifacts and does not dispatch providers or inspect raw traces.",
            "Release and dashboard review summaries preserve only compact engine, priority-count, highest-priority, no-dispatch, priority-area, and aligned-artifact metadata.",
            "Advisory reason text and raw evidence payloads are not copied into compact review indexes.",
        ),
    ),
)


def artifact_schema_registry() -> dict[str, Any]:
    return {
        "schema_version": SCHEMA_REGISTRY_VERSION,
        "artifact_count": len(ARTIFACT_SCHEMAS),
        "artifacts": [artifact_schema_payload(schema) for schema in ARTIFACT_SCHEMAS],
        "security_notes": [
            "The registry is static and does not inspect run directories, provider configs, environment variables, keyrings, or remote endpoints.",
            "Publication-safe means the artifact is designed for external bundles when generated under normal redaction policy; organizational classification can still be stricter.",
        ],
    }


def artifact_schema_payload(schema: ArtifactSchema) -> dict[str, Any]:
    return {
        "id": schema.id,
        "title": schema.title,
        "schema_version": schema.schema_version,
        "artifact_paths": list(schema.artifact_paths),
        "produced_by": list(schema.produced_by),
        "consumed_by": list(schema.consumed_by),
        "purpose": schema.purpose,
        "required_fields": list(schema.required_fields),
        "publication_safe": schema.publication_safe,
        "contains_raw_provider_payloads": schema.contains_raw_provider_payloads,
        "contains_secrets": schema.contains_secrets,
        "notes": list(schema.notes),
    }


def artifact_schema_registry_json() -> str:
    return json.dumps(artifact_schema_registry(), indent=2, sort_keys=True) + "\n"


def format_artifact_schema_registry_markdown() -> str:
    registry = artifact_schema_registry()
    lines = [
        "# AgentBlaster Artifact Schema Registry",
        "",
        f"Schema version: `{registry['schema_version']}`",
        "",
        "This static registry documents the benchmark artifacts downstream tools should expect.",
        "",
        "| Artifact | Schema | Publication safe | Raw provider payloads | Purpose |",
        "| --- | --- | --- | --- | --- |",
    ]
    for artifact in registry["artifacts"]:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{artifact['id']}`",
                    f"`{artifact['schema_version']}`",
                    str(artifact["publication_safe"]).lower(),
                    str(artifact["contains_raw_provider_payloads"]).lower(),
                    artifact["purpose"],
                ]
            )
            + " |"
        )
    lines.extend(["", "## Security Notes", ""])
    lines.extend(f"- {note}" for note in registry["security_notes"])
    return "\n".join(lines) + "\n"
